'use strict';

var path = require('path');

var paths = require('chiton/core/paths');

/**
 * Extract assets URLs associated with a webpack entry point
 *
 * @param {object} build JSON stats on a weback build
 * @param {string} entry The name of a webpack entry point
 * @param {string} extension The file extension for the requested media type
 * @returns {string[]} The paths to the entry point's assets
 */
function assets(build, entry, extension) {
  var url = build.publicPath.replace(/\/$/, '') + '/';
  var matcher = new RegExp('\.' + extension + '$');

  var files = build.assetsByChunkName[entry] || [];
  var matches = files.filter(function(file) { return matcher.test(file); });
  return matches.map(function(match) { return url + match; });
}

/**
 * Require a server-side file that is processed by webpack
 *
 * This is used to require the file generated by webpack from a server-side
 * file.  This works by following the convention that each server-side file will
 * have a build file matching its name in the server-build directory.
 *
 * @param {string} name The name of the bridge file
 * @returns {object} The required file
 * @throws If the module cannot be found
 */
function bridge(name) {
  return require(path.join(paths.build.server, name));
}

/**
 * Get information on a webpack build
 *
 * @param {string} name The internal label for the build
 * @returns {object} Information on the build
 * @throws If no stats for the build are found
 */
function stats(name) {
  return require(path.join(paths.build.root, name + '.json'));
}

module.exports = {
  assets: assets,
  bridge: bridge,
  stats: stats
};
