'use strict';

var _ = require('lodash');

var BuildStatsPlugin = require('chiton/config/webpack/plugins/build-stats');
var errors = require('chiton/core/errors');

var ConfigurationError = errors.subclass();
var StatsError = errors.subclass();

/**
 * Load statistics on a webpack build
 *
 * @param {object} config A valid webpack configuration
 * @returns {ChitonBuildStats} Details on the build
 * @throws {ConfigurationError} If build statistics are not generated by the configuration
 * @throws {StatsError} If the build statistics cannot be loaded
 */
function loadStats(config) {
  var statsPlugin = _.find(config.plugins || [], function(plugin) {
    return plugin.constructor === BuildStatsPlugin;
  });

  if (!statsPlugin) {
    throw new ConfigurationError('The configuration does not use the build-stats plugin');
  }

  try {
    return statsPlugin.loadStats();
  } catch (e) {
    throw new StatsError('The build statistics could not be loaded');
  }
}

module.exports = {
  ConfigurationError: ConfigurationError,
  loadStats: loadStats,
  StatsError: StatsError
};
